id: dbt_run
namespace: shiny_rocks.product
description: |
  Whenever all data are loaded in BigQuery, this flow will run a dbt job to transform data.

labels:
  tag: analytics

tasks:
  - id: workingdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/shiny_rocks.git
        branch: main

      - id: dbt
        type: io.kestra.plugin.dbt.cli.DbtCLI
        containerImage: ghcr.io/kestra-io/dbt-bigquery:latest
        inputFiles:
          profiles.yml: |
            shiny_rocks_dbt:
              outputs:
                dev:
                  type: bigquery
                  dataset: shiny_rocks
                  fixed_retries: 1
                  keyfile: service_account.json
                  location: EU
                  method: service-account
                  priority: interactive
                  project: kestra-sandbox
                  threads: 8
                  timeout_seconds: 300
              target: dev
          service_account.json: "{{ secret('GCP_CREDS') }}"
        commands:
          - dbt run --profiles-dir=. --project-dir=shiny_rocks_dbt

triggers:
  - id: multiple_listen_flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS
      - id: multiple
        type: io.kestra.plugin.core.condition.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          orders:
            type: io.kestra.plugin.core.condition.ExecutionFlowCondition
            namespace: shiny_rocks.product
            flowId: load_orders_bigquery
          payments:
            type: io.kestra.plugin.core.condition.ExecutionFlowCondition
            namespace: shiny_rocks.product
            flowId: load_payments_bigquery
          services:
            type: io.kestra.plugin.core.condition.ExecutionFlowCondition
            namespace: shiny_rocks.product
            flowId: load_services_bigquery
          marketing_investments:
            type: io.kestra.plugin.core.condition.ExecutionFlowCondition
            namespace: shiny_rocks.marketing
            flowId: marketing_investments_to_bigquery
          