id: load_payments_bigquery
namespace: shiny_rocks.product
description: |
  When data are generated upstream, this flow ingest the `payments` data into Google Cloud Storage and BigQuery.

labels:
  tag: load

inputs:
  - id: payments_data
    type: URI

  - id: payment_date
    type: DATE

tasks:

  - id: extract
    type: io.kestra.plugin.gcp.gcs.Upload
    serviceAccount: '{{ secret("GCP_CREDS") }}'
    from: "{{ inputs.payments_data }}"
    to: gs://shiny_rocks_project/app_log/payments/{{ inputs.payment_date }}/payments.csv

  - id: load
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    from: 
      - "{{ outputs.extract.uri }}"
    projectId: "kestra-sandbox"
    destinationTable: "shiny_rocks.payments"
    serviceAccount: '{{ secret("GCP_CREDS") }}'
    format: CSV
    autodetect: true
    csvOptions:
      fieldDelimiter: ","
    timePartitioningField: "order_date"

triggers:

  - id: get_data
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      payments_data: "{{ outputs.python.outputFiles['payments.csv'] }}"
      payment_date: "{{ outputs.run_date.value }}"
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionFlowCondition
        namespace: shiny_rocks.product
        flowId: produce_data
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - SUCCESS